language: python
puthon: 3.8
script:
  - cd PythonApplication1
  - pytest
  - cd ..

deploy:
  provider: releases
  prerelease: true
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    repo: ayz1n/Laborator6
    branch: dev
    tags: false
